services:
  choreonoid_workspace:
    build: docker
    container_name: choreonoid_workspace
    volumes:
      # ros2 workspace
      - ./ros2_ws:/root/ros2_ws
      # to tansport X11 application (require xhost local:)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    environment:
      # to transport X11 application window
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    command: bash